name: Publish to Hangar
on:
  push:
    branches:
      - master

jobs:
  publish:
    if: github.repository_owner == 'ViaVersion'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          check-latest: true
      - name: Publish
        env:
          HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
        run: ./gradlew build publishAllPublicationsToHangar
